
# Subir api
# navegar até a pasta api
# java -jar server.jar

# Espelhar ngrok
# navegar até a pasta Development
# ./ngrok http 8080

# @url = http://localhost:8080/ 
# @url = https://24a5e8b4c301.ngrok.io
@url = http://e961-2804-7f4-c2a5-9a16-99ca-aa04-2f58-9662.ngrok.io/

### Get Transactions
GET {{url}}transactions

### Post Transactions
POST {{url}}transactions
content-type: application/json
password: 1000

{
  	"value": 200.0,
  	"contact": {
  		"name": "gui",
  		"accountNumber": 1000
  	}
}